trigger:
- main

variables:
  tag: '$(Build.BuildId)'
  DOCKER_REPOSITORY_NAME: 'public.ecr.aws/z8d0d4x6/t.i/segunda-actividad'

stages:
- stage: Build
  displayName: Build image
  pool:
    name: UTB
  jobs:
  - job: BuildAndPush
    displayName: Build
    pool:
      name: UTB
    steps:
    - task: Docker@2
      inputs:
        command: 'build'
        repository: $(DOCKER_REPOSITORY_NAME)
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

- stage: push
  displayName: Build image
  dependsOn: Build
  jobs:
    - job : push
      displayName: 'Push'
      pool:
        name: utb
      steps:
      - task: ECRPushImage@1
        inputs:
           awsCredentials: 'AWS'
           AWS_REGION: "ap-southeast-2"
           imageSource: 'imagename'
           sourceImageTag: $(Build.BuildId)
           pushTag: $(Build.BuildId)
           sourceImageName: $(DOCKER_REPOSITORY_NAME)
           repositoryName: 't.i/segunda-actividad'