trigger:
- main

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  pool:
    name: UTB
  jobs:
  - job: BuildAndPush
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'AWS'
        repository: 't.i/segunda-actividad'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
