trigger:
- main

variables:
  tag: '$(Build.BuildId)'
  DOCKER_REPOSITORY_NAME: 'IMAGEN'

stages:
- stage: Build
  displayName: Build image
  pool:
    name: UTB
  jobs:
  - job: BuildAndPush
    displayName: Build
    pool:
      name: UTB
    steps:
    - task: Docker@2
      inputs:
        command: 'build'
        repository: $(DOCKER_REPOSITORY_NAME)
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)